import dotenv from 'dotenv';
import mongoose from 'mongoose';
import connectDB from './config/db.js';
import Recipe from './models/recipeModel.js';

dotenv.config();

const sampleRecipes = [
  {
    title: 'Vegetable Stir Fry',
    ingredients: ['broccoli', 'carrots', 'bell peppers', 'soy sauce', 'garlic'],
    instructions: ['Chop veggies', 'Heat oil in a wok or large pan', 'Add garlic and stir for 30 seconds', 'Add vegetables and stir fry for 5-7 minutes', 'Add soy sauce and mix well', 'Serve hot'],
    cuisine: 'Asian',
    mealType: 'Dinner',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.5,
  },
  {
    title: 'Pasta Carbonara',
    ingredients: ['pasta', 'eggs', 'bacon', 'parmesan cheese', 'black pepper'],
    instructions: ['Boil pasta according to package instructions', 'Cook bacon until crispy', 'Beat eggs with grated parmesan', 'Drain pasta, reserving some pasta water', 'Mix hot pasta with eggs and cheese', 'Add bacon and black pepper'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Quinoa Avocado Salad',
    ingredients: ['quinoa', 'avocado', 'cherry tomatoes', 'cucumber', 'lemon', 'olive oil'],
    instructions: ['Cook quinoa according to package instructions', 'Chop avocado, tomatoes, and cucumber', 'Mix vegetables with cooked quinoa', 'Dress with lemon juice and olive oil', 'Season with salt and pepper to taste'],
    cuisine: 'American',
    mealType: 'Lunch',
    dietaryRestrictions: ['Vegan'],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.2,
  },
  {
    title: 'Chicken Tikka Masala',
    ingredients: ['chicken breast', 'yogurt', 'garam masala', 'tomato sauce', 'cream', 'onion', 'garlic', 'ginger'],
    instructions: ['Marinate chicken in yogurt and spices for 1 hour', 'Grill or bake chicken until cooked', 'Sauté onion, garlic, and ginger', 'Add tomato sauce and spices', 'Add cooked chicken and simmer', 'Stir in cream before serving'],
    cuisine: 'Indian',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Greek Salad',
    ingredients: ['cucumber', 'tomatoes', 'red onion', 'feta cheese', 'olives', 'olive oil', 'lemon juice', 'oregano'],
    instructions: ['Chop cucumber, tomatoes, and red onion', 'Add crumbled feta cheese and olives', 'Mix olive oil, lemon juice, and oregano for dressing', 'Pour dressing over salad and toss'],
    cuisine: 'Greek',
    mealType: 'Lunch',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.3,
  },
  {
    title: 'Beef Tacos',
    ingredients: ['ground beef', 'taco seasoning', 'tortillas', 'lettuce', 'tomato', 'cheese', 'sour cream', 'avocado'],
    instructions: ['Brown ground beef in a pan', 'Add taco seasoning and water', 'Simmer until sauce thickens', 'Warm tortillas', 'Assemble tacos with beef and toppings'],
    cuisine: 'Mexican',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Mushroom Risotto',
    ingredients: ['arborio rice', 'mushrooms', 'onion', 'garlic', 'white wine', 'vegetable broth', 'parmesan cheese', 'butter'],
    instructions: ['Sauté mushrooms, onion, and garlic', 'Add rice and stir to coat with oil', 'Add wine and simmer until absorbed', 'Gradually add hot broth, stirring constantly', 'Cook until rice is creamy and tender', 'Stir in parmesan and butter'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.4,
  },
  {
    title: 'Chocolate Chip Cookies',
    ingredients: ['flour', 'butter', 'sugar', 'brown sugar', 'eggs', 'vanilla extract', 'baking soda', 'salt', 'chocolate chips'],
    instructions: ['Cream butter and sugars until fluffy', 'Beat in eggs and vanilla', 'Mix dry ingredients separately', 'Combine wet and dry ingredients', 'Fold in chocolate chips', 'Drop spoonfuls onto baking sheet', 'Bake at 350°F for 10-12 minutes'],
    cuisine: 'American',
    mealType: 'Dessert',
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Sushi Rolls',
    ingredients: ['sushi rice', 'nori sheets', 'cucumber', 'avocado', 'carrot', 'soy sauce', 'wasabi', 'pickled ginger'],
    instructions: ['Prepare sushi rice according to package', 'Place nori sheet on bamboo mat', 'Spread rice evenly on nori', 'Add fillings in a line', 'Roll tightly using bamboo mat', 'Cut into pieces with wet knife', 'Serve with soy sauce, wasabi, and ginger'],
    cuisine: 'Japanese',
    mealType: 'Lunch',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Beef Stroganoff',
    ingredients: ['beef strips', 'onion', 'mushrooms', 'garlic', 'beef broth', 'sour cream', 'flour', 'egg noodles', 'butter', 'parsley'],
    instructions: ['Cook egg noodles according to package', 'Brown beef strips in butter', 'Remove beef and sauté onions, garlic, and mushrooms', 'Add flour to make a roux', 'Stir in beef broth and bring to simmer', 'Return beef to pan', 'Stir in sour cream', 'Serve over noodles and garnish with parsley'],
    cuisine: 'Russian',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.5,
  },
  {
    title: 'Vegetable Lasagna',
    ingredients: ['lasagna noodles', 'zucchini', 'spinach', 'ricotta cheese', 'mozzarella cheese', 'parmesan cheese', 'tomato sauce', 'onion', 'garlic', 'Italian herbs'],
    instructions: ['Sauté onion, garlic, and vegetables', 'Mix ricotta with herbs and parmesan', 'Layer sauce, noodles, vegetables, and cheeses', 'Repeat layers ending with cheese on top', 'Cover with foil and bake at 375°F for 25 minutes', 'Remove foil and bake 10 more minutes until cheese is golden'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 30,
    cookTime: 45,
    servings: 8,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Chicken Noodle Soup',
    ingredients: ['chicken breast', 'carrots', 'celery', 'onion', 'garlic', 'chicken broth', 'egg noodles', 'thyme', 'bay leaf', 'parsley'],
    instructions: ['Sauté onion, carrots, celery, and garlic', 'Add chicken broth, chicken, and herbs', 'Simmer until chicken is cooked', 'Remove chicken and shred', 'Return chicken to pot and add noodles', 'Cook until noodles are tender', 'Garnish with fresh parsley'],
    cuisine: 'American',
    mealType: 'Lunch',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Banana Bread',
    ingredients: ['ripe bananas', 'flour', 'butter', 'sugar', 'eggs', 'baking soda', 'salt', 'vanilla extract', 'cinnamon'],
    instructions: ['Mash bananas in a large bowl', 'Cream butter and sugar, then add eggs and vanilla', 'Mix in mashed bananas', 'Add dry ingredients and mix until just combined', 'Pour into greased loaf pan', 'Bake at 350°F for 55-60 minutes'],
    cuisine: 'American',
    mealType: 'Breakfast',
    prepTime: 15,
    cookTime: 60,
    servings: 10,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Pad Thai',
    ingredients: ['rice noodles', 'tofu', 'bean sprouts', 'eggs', 'green onions', 'peanuts', 'lime', 'fish sauce', 'tamarind paste', 'garlic', 'sugar'],
    instructions: ['Soak rice noodles in hot water until soft', 'Mix sauce with fish sauce, tamarind, and sugar', 'Stir-fry garlic and tofu', 'Push to side and scramble eggs', 'Add noodles and sauce', 'Toss in bean sprouts and green onions', 'Garnish with peanuts and lime wedges'],
    cuisine: 'Thai',
    mealType: 'Dinner',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Guacamole',
    ingredients: ['avocados', 'lime juice', 'red onion', 'tomato', 'cilantro', 'jalapeño', 'garlic', 'salt'],
    instructions: ['Mash avocados with lime juice', 'Finely dice onion, tomato, jalapeño, and garlic', 'Chop cilantro', 'Mix all ingredients together', 'Season with salt to taste', 'Serve with tortilla chips'],
    cuisine: 'Mexican',
    mealType: 'Appetizer',
    dietaryRestrictions: ['Vegan'],
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Chocolate Chip Cookies (Classic)',
    ingredients: ['flour', 'butter', 'brown sugar', 'white sugar', 'eggs', 'vanilla extract', 'baking soda', 'chocolate chips'],
    instructions: ['Cream butter and sugars together', 'Beat in eggs and vanilla', 'Mix in dry ingredients', 'Fold in chocolate chips', 'Drop spoonfuls onto baking sheet', 'Bake at 350°F for 10-12 minutes'],
    cuisine: 'American',
    mealType: 'Dessert',
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Sushi Rolls',
    ingredients: ['sushi rice', 'nori sheets', 'cucumber', 'avocado', 'carrot', 'soy sauce', 'wasabi', 'pickled ginger'],
    instructions: ['Prepare sushi rice according to package', 'Place nori sheet on bamboo mat', 'Spread rice on nori', 'Add fillings in a line', 'Roll tightly using bamboo mat', 'Slice into pieces', 'Serve with soy sauce, wasabi, and ginger'],
    cuisine: 'Japanese',
    mealType: 'Lunch',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 30,
    cookTime: 15,
    servings: 2,
    difficulty: 'Hard',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'French Onion Soup',
    ingredients: ['onions', 'beef broth', 'butter', 'flour', 'baguette', 'gruyere cheese', 'thyme', 'bay leaf'],
    instructions: ['Caramelize onions in butter (30-40 minutes)', 'Add flour and cook for 1 minute', 'Add broth, thyme, and bay leaf', 'Simmer for 30 minutes', 'Pour into oven-safe bowls', 'Top with baguette slices and cheese', 'Broil until cheese is melted and golden'],
    cuisine: 'French',
    mealType: 'Starter',
    prepTime: 15,
    cookTime: 75,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Pad Thai',
    ingredients: ['rice noodles', 'chicken', 'eggs', 'bean sprouts', 'green onions', 'peanuts', 'lime', 'fish sauce', 'tamarind paste', 'sugar'],
    instructions: ['Soak rice noodles in hot water', 'Mix sauce with fish sauce, tamarind, and sugar', 'Stir-fry chicken until cooked', 'Push chicken aside and scramble eggs', 'Add drained noodles and sauce', 'Toss in bean sprouts and green onions', 'Garnish with peanuts and lime wedges'],
    cuisine: 'Thai',
    mealType: 'Dinner',
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Beef Bourguignon',
    ingredients: ['beef chuck', 'bacon', 'red wine', 'beef broth', 'onions', 'carrots', 'mushrooms', 'garlic', 'thyme', 'bay leaf'],
    instructions: ['Brown bacon and remove from pot', 'Sear beef cubes and remove', 'Sauté vegetables in same pot', 'Add beef, bacon, wine, broth, and herbs', 'Simmer covered for 3 hours', 'Serve with mashed potatoes'],
    cuisine: 'French',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 180,
    servings: 6,
    difficulty: 'Hard',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Caprese Salad',
    ingredients: ['tomatoes', 'fresh mozzarella', 'basil leaves', 'olive oil', 'balsamic glaze', 'salt', 'black pepper'],
    instructions: ['Slice tomatoes and mozzarella', 'Arrange alternating slices on a plate', 'Tuck basil leaves between slices', 'Drizzle with olive oil and balsamic glaze', 'Season with salt and pepper'],
    cuisine: 'Italian',
    mealType: 'Starter',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.5,
  },
  {
    title: 'Chicken Fajitas',
    ingredients: ['chicken breast', 'bell peppers', 'onion', 'lime', 'tortillas', 'cumin', 'chili powder', 'garlic powder'],
    instructions: ['Slice chicken, peppers, and onions', 'Season chicken with spices', 'Cook chicken in hot pan until done', 'Remove chicken and cook vegetables', 'Combine chicken and vegetables', 'Serve with warm tortillas and lime wedges'],
    cuisine: 'Mexican',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Banana Bread',
    ingredients: ['ripe bananas', 'flour', 'butter', 'sugar', 'eggs', 'baking soda', 'salt', 'vanilla extract'],
    instructions: ['Preheat oven to 350°F', 'Mash bananas in a large bowl', 'Mix in melted butter', 'Stir in sugar, egg, and vanilla', 'Add flour, baking soda, and salt', 'Pour into greased loaf pan', 'Bake for 55-60 minutes'],
    cuisine: 'American',
    mealType: 'Breakfast',
    prepTime: 15,
    cookTime: 60,
    servings: 8,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Hummus',
    ingredients: ['chickpeas', 'tahini', 'lemon juice', 'garlic', 'olive oil', 'cumin', 'salt'],
    instructions: ['Drain and rinse chickpeas', 'Blend chickpeas, tahini, lemon juice, and garlic', 'Add olive oil while blending', 'Season with cumin and salt', 'Serve with a drizzle of olive oil'],
    cuisine: 'Middle Eastern',
    mealType: 'Appetizer',
    dietaryRestrictions: ['Vegan'],
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.4,
  },
  {
    title: 'Beef Wellington',
    ingredients: ['beef tenderloin', 'mushrooms', 'puff pastry', 'prosciutto', 'dijon mustard', 'egg', 'thyme', 'garlic'],
    instructions: ['Sear beef tenderloin and let cool', 'Make mushroom duxelles', 'Spread mustard on beef', 'Wrap beef in prosciutto and mushroom mixture', 'Wrap in puff pastry', 'Brush with egg wash', 'Bake at 425°F for 40-45 minutes'],
    cuisine: 'British',
    mealType: 'Dinner',
    prepTime: 45,
    cookTime: 45,
    servings: 6,
    difficulty: 'Hard',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Guacamole',
    ingredients: ['avocados', 'lime juice', 'red onion', 'tomato', 'cilantro', 'jalapeño', 'salt', 'garlic'],
    instructions: ['Mash avocados in a bowl', 'Add lime juice to prevent browning', 'Finely chop onion, tomato, cilantro, and jalapeño', 'Mix all ingredients together', 'Season with salt and minced garlic'],
    cuisine: 'Mexican',
    mealType: 'Appetizer',
    dietaryRestrictions: ['Vegan'],
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Chicken Noodle Soup',
    ingredients: ['chicken', 'carrots', 'celery', 'onion', 'chicken broth', 'egg noodles', 'thyme', 'bay leaf'],
    instructions: ['Simmer chicken in broth until cooked', 'Remove chicken and shred', 'Add chopped vegetables to broth', 'Add noodles and cook until tender', 'Return shredded chicken to pot', 'Season with herbs and salt'],
    cuisine: 'American',
    mealType: 'Soup',
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Tiramisu',
    ingredients: ['ladyfingers', 'espresso', 'mascarpone cheese', 'eggs', 'sugar', 'cocoa powder', 'rum'],
    instructions: ['Separate eggs and beat yolks with sugar', 'Mix in mascarpone cheese', 'Beat egg whites until stiff and fold in', 'Dip ladyfingers in espresso and rum', 'Layer soaked ladyfingers and cream mixture', 'Dust with cocoa powder', 'Refrigerate for at least 4 hours'],
    cuisine: 'Italian',
    mealType: 'Dessert',
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Shakshuka',
    ingredients: ['eggs', 'tomatoes', 'bell peppers', 'onion', 'garlic', 'cumin', 'paprika', 'chili powder', 'feta cheese'],
    instructions: ['Sauté onions and peppers until soft', 'Add garlic and spices', 'Add tomatoes and simmer', 'Make wells in sauce and crack eggs into them', 'Cover and cook until eggs are set', 'Sprinkle with feta cheese and herbs'],
    cuisine: 'Middle Eastern',
    mealType: 'Breakfast',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Pho',
    ingredients: ['rice noodles', 'beef broth', 'beef sirloin', 'onion', 'ginger', 'star anise', 'cinnamon', 'bean sprouts', 'basil', 'lime'],
    instructions: ['Simmer broth with spices for 3 hours', 'Cook rice noodles according to package', 'Slice beef very thinly', 'Place noodles in bowl and top with raw beef', 'Pour hot broth over to cook beef', 'Garnish with bean sprouts, basil, and lime'],
    cuisine: 'Vietnamese',
    mealType: 'Soup',
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    difficulty: 'Hard',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Caesar Salad',
    ingredients: ['romaine lettuce', 'parmesan cheese', 'croutons', 'eggs', 'garlic', 'dijon mustard', 'anchovy paste', 'lemon juice', 'olive oil'],
    instructions: ['Make dressing by whisking egg yolk, garlic, mustard, anchovy paste, and lemon juice', 'Slowly add olive oil while whisking', 'Tear lettuce into bite-sized pieces', 'Toss lettuce with dressing', 'Add parmesan and croutons'],
    cuisine: 'American',
    mealType: 'Salad',
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.5,
  },
  {
    title: 'Butter Chicken',
    ingredients: ['chicken thighs', 'yogurt', 'tomato sauce', 'cream', 'butter', 'garam masala', 'turmeric', 'cumin', 'ginger', 'garlic'],
    instructions: ['Marinate chicken in yogurt and spices', 'Grill or bake chicken until cooked', 'Sauté garlic and ginger', 'Add tomato sauce and spices', 'Simmer and add cream and butter', 'Add cooked chicken and simmer', 'Serve with rice or naan'],
    cuisine: 'Indian',
    mealType: 'Dinner',
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Apple Pie',
    ingredients: ['flour', 'butter', 'sugar', 'apples', 'cinnamon', 'nutmeg', 'lemon juice', 'salt'],
    instructions: ['Make pie dough with flour, butter, sugar, and salt', 'Chill dough for 1 hour', 'Peel and slice apples', 'Mix apples with sugar, spices, and lemon juice', 'Roll out dough and line pie dish', 'Add apple filling', 'Top with second crust or lattice', 'Bake at 375°F for 45-50 minutes'],
    cuisine: 'American',
    mealType: 'Dessert',
    prepTime: 30,
    cookTime: 50,
    servings: 8,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Ratatouille',
    ingredients: ['eggplant', 'zucchini', 'bell peppers', 'tomatoes', 'onion', 'garlic', 'herbs de provence', 'olive oil'],
    instructions: ['Slice all vegetables thinly', 'Sauté onion and garlic', 'Add tomatoes to make sauce', 'Arrange sliced vegetables in pattern over sauce', 'Drizzle with olive oil and sprinkle with herbs', 'Bake at 375°F for 45 minutes'],
    cuisine: 'French',
    mealType: 'Dinner',
    dietaryRestrictions: ['Vegan'],
    prepTime: 30,
    cookTime: 45,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Beef Stroganoff',
    ingredients: ['beef sirloin', 'mushrooms', 'onion', 'beef broth', 'sour cream', 'flour', 'butter', 'egg noodles'],
    instructions: ['Slice beef thinly and season', 'Sauté beef quickly and remove from pan', 'Cook mushrooms and onions in same pan', 'Add flour to make roux', 'Add broth and simmer', 'Stir in sour cream', 'Return beef to pan', 'Serve over cooked egg noodles'],
    cuisine: 'Russian',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Gazpacho',
    ingredients: ['tomatoes', 'cucumber', 'bell pepper', 'red onion', 'garlic', 'olive oil', 'red wine vinegar', 'bread'],
    instructions: ['Roughly chop vegetables', 'Blend all ingredients until smooth', 'Strain if desired for smoother texture', 'Chill for at least 2 hours', 'Serve cold with garnishes'],
    cuisine: 'Spanish',
    mealType: 'Soup',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.4,
  },
  {
    title: 'Chicken Parmesan',
    ingredients: ['chicken breast', 'breadcrumbs', 'parmesan cheese', 'mozzarella cheese', 'eggs', 'tomato sauce', 'basil', 'pasta'],
    instructions: ['Pound chicken to even thickness', 'Dip in egg then breadcrumb mixture', 'Fry until golden and cooked through', 'Top with tomato sauce and cheeses', 'Bake until cheese melts', 'Serve over pasta'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Lemon Bars',
    ingredients: ['flour', 'butter', 'sugar', 'eggs', 'lemon juice', 'lemon zest', 'powdered sugar'],
    instructions: ['Make shortbread crust with flour, butter, and sugar', 'Bake crust at 350°F for 15-20 minutes', 'Whisk eggs, sugar, lemon juice, and zest', 'Pour over baked crust', 'Bake for additional 20 minutes', 'Cool completely and dust with powdered sugar'],
    cuisine: 'American',
    mealType: 'Dessert',
    prepTime: 15,
    cookTime: 40,
    servings: 12,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Falafel',
    ingredients: ['dried chickpeas', 'onion', 'garlic', 'parsley', 'cilantro', 'cumin', 'coriander', 'baking soda'],
    instructions: ['Soak chickpeas overnight', 'Process with herbs and spices', 'Form into balls or patties', 'Fry until golden and crispy', 'Serve in pita with tahini sauce'],
    cuisine: 'Middle Eastern',
    mealType: 'Lunch',
    dietaryRestrictions: ['Vegan'],
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Beef and Broccoli',
    ingredients: ['beef flank steak', 'broccoli', 'soy sauce', 'oyster sauce', 'garlic', 'ginger', 'cornstarch', 'sesame oil'],
    instructions: ['Slice beef thinly against the grain', 'Marinate beef in soy sauce mixture', 'Blanch broccoli briefly', 'Stir-fry beef until just cooked', 'Add broccoli and sauce', 'Thicken with cornstarch slurry', 'Serve with rice'],
    cuisine: 'Chinese',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Pancakes',
    ingredients: ['flour', 'milk', 'eggs', 'sugar', 'baking powder', 'salt', 'butter', 'vanilla extract'],
    instructions: ['Mix dry ingredients in one bowl', 'Whisk wet ingredients in another bowl', 'Combine wet and dry ingredients', 'Heat griddle or pan', 'Pour batter to form pancakes', 'Flip when bubbles form', 'Cook until golden'],
    cuisine: 'American',
    mealType: 'Breakfast',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Lasagna',
    ingredients: ['ground beef', 'onion', 'garlic', 'tomato sauce', 'lasagna noodles', 'ricotta cheese', 'mozzarella cheese', 'parmesan cheese', 'eggs', 'Italian herbs'],
    instructions: ['Make meat sauce with beef, onion, garlic, and tomato sauce', 'Mix ricotta, egg, and parmesan', 'Layer noodles, meat sauce, and cheese mixture', 'Top with mozzarella', 'Bake covered at 375°F for 25 minutes', 'Uncover and bake 25 more minutes'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 60,
    servings: 8,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Miso Soup',
    ingredients: ['dashi stock', 'miso paste', 'tofu', 'green onions', 'seaweed', 'mushrooms'],
    instructions: ['Heat dashi stock (don\'t boil)', 'Dissolve miso paste in ladle with some stock', 'Add dissolved miso to pot', 'Add tofu and mushrooms', 'Simmer briefly', 'Garnish with green onions and seaweed'],
    cuisine: 'Japanese',
    mealType: 'Soup',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.5,
  },
  {
    title: 'Chicken Curry',
    ingredients: ['chicken thighs', 'onion', 'garlic', 'ginger', 'curry powder', 'coconut milk', 'tomatoes', 'cilantro'],
    instructions: ['Sauté onion, garlic, and ginger', 'Add curry powder and cook briefly', 'Add chicken and brown', 'Add tomatoes and coconut milk', 'Simmer until chicken is tender', 'Garnish with cilantro'],
    cuisine: 'Indian',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Chocolate Mousse',
    ingredients: ['dark chocolate', 'eggs', 'sugar', 'heavy cream', 'butter', 'vanilla extract'],
    instructions: ['Melt chocolate and butter', 'Separate eggs', 'Beat yolks with sugar', 'Add chocolate to yolk mixture', 'Whip egg whites until stiff', 'Whip cream separately', 'Fold whites then cream into chocolate mixture', 'Chill for at least 2 hours'],
    cuisine: 'French',
    mealType: 'Dessert',
    prepTime: 25,
    cookTime: 10,
    servings: 6,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Paella',
    ingredients: ['rice', 'saffron', 'chicken', 'shrimp', 'mussels', 'bell peppers', 'peas', 'tomatoes', 'onion', 'garlic'],
    instructions: ['Sauté onion and garlic', 'Add bell peppers and tomatoes', 'Add rice and saffron', 'Add broth and simmer', 'Add chicken, then seafood', 'Add peas at the end', 'Let develop crust on bottom', 'Garnish with lemon wedges'],
    cuisine: 'Spanish',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: 'Hard',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Potato Leek Soup',
    ingredients: ['potatoes', 'leeks', 'onion', 'garlic', 'vegetable broth', 'cream', 'butter', 'thyme'],
    instructions: ['Sauté leeks and onion in butter', 'Add garlic and cook briefly', 'Add potatoes and broth', 'Simmer until potatoes are tender', 'Blend until smooth', 'Stir in cream', 'Season with salt and pepper'],
    cuisine: 'French',
    mealType: 'Soup',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Chicken Alfredo',
    ingredients: ['fettuccine pasta', 'chicken breast', 'heavy cream', 'butter', 'garlic', 'parmesan cheese', 'parsley'],
    instructions: ['Cook pasta according to package', 'Season and cook chicken until done', 'Slice chicken into strips', 'Sauté garlic in butter', 'Add cream and simmer', 'Stir in parmesan until melted', 'Toss with pasta and chicken', 'Garnish with parsley'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Pumpkin Pie',
    ingredients: ['pie crust', 'pumpkin puree', 'condensed milk', 'eggs', 'cinnamon', 'ginger', 'nutmeg', 'cloves'],
    instructions: ['Preheat oven to 425°F', 'Mix pumpkin, milk, eggs, and spices', 'Pour into pie crust', 'Bake for 15 minutes', 'Reduce heat to 350°F', 'Bake for 40-50 more minutes', 'Cool completely before serving'],
    cuisine: 'American',
    mealType: 'Dessert',
    prepTime: 15,
    cookTime: 65,
    servings: 8,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Chicken Enchiladas',
    ingredients: ['tortillas', 'chicken', 'enchilada sauce', 'cheese', 'onion', 'bell pepper', 'sour cream', 'cilantro'],
    instructions: ['Cook and shred chicken', 'Sauté onions and peppers', 'Mix vegetables with chicken', 'Dip tortillas in sauce', 'Fill with chicken mixture', 'Roll and place in baking dish', 'Top with more sauce and cheese', 'Bake at 350°F for 20-25 minutes'],
    cuisine: 'Mexican',
    mealType: 'Dinner',
    prepTime: 25,
    cookTime: 25,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Creme Brulee',
    ingredients: ['heavy cream', 'vanilla bean', 'egg yolks', 'sugar'],
    instructions: ['Heat cream with vanilla bean', 'Whisk egg yolks with sugar', 'Temper eggs with hot cream', 'Strain mixture', 'Pour into ramekins', 'Bake in water bath at 325°F for 30-35 minutes', 'Chill for at least 2 hours', 'Top with sugar and torch until caramelized'],
    cuisine: 'French',
    mealType: 'Dessert',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Hard',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Vegetable Curry',
    ingredients: ['potatoes', 'carrots', 'peas', 'cauliflower', 'onion', 'garlic', 'ginger', 'curry powder', 'coconut milk', 'tomatoes'],
    instructions: ['Sauté onion, garlic, and ginger', 'Add curry powder and cook briefly', 'Add vegetables and stir to coat', 'Add tomatoes and coconut milk', 'Simmer until vegetables are tender', 'Serve with rice or naan'],
    cuisine: 'Indian',
    mealType: 'Dinner',
    dietaryRestrictions: ['Vegan'],
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.6,
  },
  {
    title: 'Beef Chili',
    ingredients: ['ground beef', 'kidney beans', 'black beans', 'tomatoes', 'onion', 'bell pepper', 'garlic', 'chili powder', 'cumin', 'oregano'],
    instructions: ['Brown beef and drain fat', 'Sauté onion, pepper, and garlic', 'Add spices and cook briefly', 'Add tomatoes and beans', 'Simmer for at least 30 minutes', 'Serve with toppings of choice'],
    cuisine: 'American',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Lemon Chicken',
    ingredients: ['chicken breast', 'lemon', 'garlic', 'chicken broth', 'white wine', 'butter', 'capers', 'parsley'],
    instructions: ['Pound chicken to even thickness', 'Season and dredge in flour', 'Sauté until golden and cooked', 'Remove chicken and keep warm', 'Add garlic to pan', 'Deglaze with wine and add broth', 'Add lemon juice and capers', 'Return chicken to pan briefly', 'Finish with butter and parsley'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Cheesecake',
    ingredients: ['graham crackers', 'butter', 'cream cheese', 'sugar', 'eggs', 'sour cream', 'vanilla extract', 'lemon zest'],
    instructions: ['Make crust with crushed graham crackers and butter', 'Bake crust for 10 minutes', 'Beat cream cheese and sugar until smooth', 'Add eggs one at a time', 'Stir in sour cream, vanilla, and zest', 'Pour over crust', 'Bake at 325°F for 55-60 minutes', 'Cool completely and chill overnight'],
    cuisine: 'American',
    mealType: 'Dessert',
    prepTime: 30,
    cookTime: 70,
    servings: 12,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.9,
  },
  {
    title: 'Shrimp Scampi',
    ingredients: ['shrimp', 'linguine', 'garlic', 'white wine', 'lemon juice', 'butter', 'red pepper flakes', 'parsley'],
    instructions: ['Cook pasta according to package', 'Sauté garlic in butter', 'Add shrimp and cook until pink', 'Add wine, lemon juice, and red pepper', 'Toss with pasta', 'Garnish with parsley'],
    cuisine: 'Italian',
    mealType: 'Dinner',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Vegetable Biryani',
    ingredients: ['basmati rice', 'mixed vegetables', 'onion', 'garlic', 'ginger', 'biryani masala', 'yogurt', 'saffron', 'mint', 'cilantro'],
    instructions: ['Soak rice for 30 minutes', 'Sauté onion, garlic, and ginger', 'Add vegetables and spices', 'Layer partially cooked rice and vegetables', 'Add saffron milk and herbs', 'Cover tightly and cook on low heat', 'Let rest before serving'],
    cuisine: 'Indian',
    mealType: 'Dinner',
    dietaryRestrictions: ['Vegetarian'],
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: 'Hard',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Fish Tacos',
    ingredients: ['white fish', 'lime', 'cumin', 'chili powder', 'cabbage slaw', 'avocado', 'sour cream', 'corn tortillas'],
    instructions: ['Season fish with spices', 'Grill or pan-fry until flaky', 'Warm tortillas', 'Make lime crema with sour cream', 'Assemble tacos with fish, slaw, and toppings'],
    cuisine: 'Mexican',
    mealType: 'Dinner',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.8,
  },
  {
    title: 'Chicken Pot Pie',
    ingredients: ['chicken', 'carrots', 'peas', 'celery', 'onion', 'flour', 'chicken broth', 'cream', 'pie crust', 'thyme'],
    instructions: ['Cook and shred chicken', 'Sauté vegetables until soft', 'Add flour to make roux', 'Add broth and cream', 'Add chicken and seasonings', 'Pour into pie dish', 'Top with pie crust', 'Bake at 375°F for 30-35 minutes'],
    cuisine: 'American',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 35,
    servings: 6,
    difficulty: 'Medium',
    isGenerated: false,
    rating: 4.7,
  },
  {
    title: 'Chocolate Chip Pancakes',
    ingredients: ['flour', 'milk', 'eggs', 'sugar', 'baking powder', 'salt', 'vanilla extract', 'chocolate chips'],
    instructions: ['Mix dry ingredients in one bowl', 'Whisk wet ingredients in another bowl', 'Combine wet and dry ingredients', 'Fold in chocolate chips', 'Heat griddle or pan', 'Pour batter to form pancakes', 'Flip when bubbles form', 'Cook until golden'],
    cuisine: 'American',
    mealType: 'Breakfast',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    isGenerated: false,
    rating: 4.8,
  }
];

async function run() {
  try {
    const uri = process.env.MONGO_URI;
    await mongoose.connect(uri|| 'mongodb://localhost:27017/recipe_generator_db');
    await Recipe.deleteMany({});
    const userId = new mongoose.Types.ObjectId();
    const docs = sampleRecipes.map((r) => ({ ...r, user: userId }));
    await Recipe.insertMany(docs);
    console.log('Seeded recipes');
    process.exit(0);
  } catch (e) {
    console.error(e);
    process.exit(1);
  }
}

run();


